name: Conditional Parallel Jobs

on:
  push:
    branches:
      - 'feature/*'
      - 'master'
      - 'development'

jobs:
  folder1:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development' || (github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' && contains(github.event.head_commit.message, 'Folder1/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Folder1 job
        run: echo "Running Folder1 job"

  folder2:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development' || (github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' && contains(github.event.head_commit.message, 'Folder2/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Folder2 job
        run: echo "Running Folder2 job"

  folder3:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development' || (github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' && contains(github.event.head_commit.message, 'Folder3/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Folder3 job
        run: echo "Running Folder3 job"

  folder4:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development' || (github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' && contains(github.event.head_commit.message, 'Folder4/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Folder4 job
        run: echo "Running Folder4 job"
