name: Parallel Jobs

on:
  push:
    branches:
      - feature/*
      - development
      - master

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'Folder1/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your job steps here

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'Folder2/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your job steps here

  job3:
    name: Job 3
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'Folder3/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your job steps here

  job4:
    name: Job 4
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'Folder4/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your job steps here
