name: Conditional Job Execution

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - development
      - master

jobs:
  Folder1:
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/development' && github.ref != 'refs/heads/master' && (contains(join(github.event.commits.*.modified), 'Folder1/') || contains(join(github.event.commits.*.added), 'Folder1/') || contains(join(github.event.commits.*.removed), 'Folder1/')))
      || (github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Folder1 job
        run: echo "Running job for Folder1"

  Folder2:
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/development' && github.ref != 'refs/heads/master' && (contains(join(github.event.commits.*.modified), 'Folder2/') || contains(join(github.event.commits.*.added), 'Folder2/') || contains(join(github.event.commits.*.removed), 'Folder2/')))
      || (github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Folder2 job
        run: echo "Running job for Folder2"

  Folder3:
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/development' && github.ref != 'refs/heads/master' && (contains(join(github.event.commits.*.modified), 'Folder3/') || contains(join(github.event.commits.*.added), 'Folder3/') || contains(join(github.event.commits.*.removed), 'Folder3/')))
      || (github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Folder3 job
        run: echo "Running job for Folder3"

  Folder4:
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/development' && github.ref != 'refs/heads/master' && (contains(join(github.event.commits.*.modified), 'Folder4/') || contains(join(github.event.commits.*.added), 'Folder4/') || contains(join(github.event.commits.*.removed), 'Folder4/')))
      || (github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Folder4 job
        run: echo "Running job for Folder4"
