name: Check Code Changes

on:
  push:
    branches:
      - main

jobs:
  check_changes_folder1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for code changes in folder1
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^Folder1'; then
            echo "Code changes detected in folder1."
          else
            echo "No code changes in folder1."
          fi

  check_changes_folder2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for code changes in folder2
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^Folder2'; then
            echo "Code changes detected in folder2."
          else
            echo "No code changes in folder2."
          fi

  check_changes_folder3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for code changes in folder3
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^Folder3'; then
            echo "Code changes detected in folder3."
          else
            echo "No code changes in folder3."
          fi

  check_changes_folder4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for code changes in folder4
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^Folder4'; then
            echo "Code changes detected in folder4."
          else
            echo "No code changes in folder4."
          fi
