name: Conditional Jobs

on:
  push:
    branches:
      - master
      - development
      - feature/*
    paths:
      - 'Folder1/**'
      - 'Folder2/**'
      - 'Folder3/**'
      - 'Folder4/**'

jobs:
  folder1_job:
    if: |
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/development' ||
      (startsWith(github.ref, 'refs/heads/feature/') && contains(join(github.event.push.commits.*.modified, ' '), 'Folder1/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Folder1 job
        run: echo "Running job for Folder1"

  folder2_job:
    if: |
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/development' ||
      (startsWith(github.ref, 'refs/heads/feature/') && contains(github.event.head_commit.modified, 'Folder2/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Folder2 job
        run: echo "Running job for Folder2"

  folder3_job:
    if: |
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/development' ||
      (startsWith(github.ref, 'refs/heads/feature/') && contains(github.event.head_commit.modified, 'Folder3/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Folder3 job
        run: echo "Running job for Folder3"

  folder4_job:
    if: |
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/development' ||
      (startsWith(github.ref, 'refs/heads/feature/') && contains(github.event.head_commit.modified, 'Folder4/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Folder4 job
        run: echo "Running job for Folder4"
