name: CI

on:
  push:
    branches:
      - master
      - development
      - 'feature/*'
    paths:
      - 'Folder1/**'
      - 'Folder2/**'
      - 'Folder3/**'
      - 'Folder4/**'

jobs:
  Folder1:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature/*' && contains(github.event.paths, 'Folder1/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}
      - name: Run Folder1 job
        run: |
          echo "Running job for Folder1"

  Folder2:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature/*' && contains(github.event.paths, 'Folder2/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}
      - name: Run Folder2 job
        run: |
          echo "Running job for Folder1"

  Folder3:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature/*' && contains(github.event.paths, 'Folder3/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}
      - name: Run Folder3 job
        run: |
          echo "Running job for Folder1"

  Folder4:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature/*' && contains(github.event.paths, 'Folder4/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}
      - name: Run Folder4 job
        run: |
          echo "Running job for Folder1"
