name: CI

on:
  push:
    branches:
      - master
      - development
      - feature/*  # Trigger for feature branches
  pull_request:  # Optional: Trigger for pull requests (consider security implications)

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [Folder1, Folder2, Folder3, Folder4]
    steps:
      - uses: actions/checkout@v3

      - name: Identify changed files
        id: changed_files
        run: |
          git diff --name-only ${{ github.sha }} HEAD > changed_files.txt

      - name: Check for changes in specific folder
        run: |
          if grep -qE "^${{ matrix.folder }}/" changed_files.txt; then
            echo "Changes detected in ${{ matrix.folder }}"
          else
            echo "No changes detected in ${{ matrix.folder }}"
            exit 1  # Skip this job for unchanged folders
          fi

      - name: Check branch name (optional)
        if: ${{ github.ref == 'refs/heads/feature/*' }}  # Only for feature branches
        run: |
          echo "Running on feature branch: ${{ github.ref }}"

      - name: Setup (replace with your specific setup steps)
        # ...

      - name: Build (replace with your build command)
        run: |
          cd ${{ matrix.folder }}
          # ...

      - name: Test (replace with your test commands)
        run: |
          cd ${{ matrix.folder }}
          # ...

  # Optional: Additional jobs for deployment, security scans, etc.

