name: CI

on:
  push:
    branches:
      - master
      - development
      - 'feature/*'

jobs:
  Folder1:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development' || (github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' && contains(github.event.head_commit.message, 'Folder1/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Folder1 specific job
        run: |
          echo "Running Folder1 job"
          # Add your Folder1 specific commands here

  Folder2:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development' || (github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' && contains(github.event.head_commit.message, 'Folder2/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Folder2 specific job
        run: |
          echo "Running Folder2 job"
          # Add your Folder2 specific commands here

  Folder3:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development' || (github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' && contains(github.event.head_commit.message, 'Folder3/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Folder3 specific job
        run: |
          echo "Running Folder3 job"
          # Add your Folder3 specific commands here

  Folder4:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development' || (github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' && contains(github.event.head_commit.message, 'Folder4/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Folder4 specific job
        run: |
          echo "Running Folder4 job"
          # Add your Folder4 specific commands here
