name: Conditional Pipelines

on:
  push:
    branches:
      - master
      - development
      - 'feature/*'
    paths:
      - 'Folder1/**'
      - 'Folder2/**'
      - 'Folder3/**'
      - 'Folder4/**'

jobs:
  job1:
    name: Folder1 Job
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/development' ||
      (github.ref != 'refs/heads/master' &&
      github.ref != 'refs/heads/development' &&
      github.event_name == 'push' &&
      contains(github.event.head_commit.message, 'Folder1'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: Folder1
      - name: Run Folder1 specific job
        run: echo "Running Folder1 job"

  job2:
    name: Folder2 Job
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/development' ||
      (github.ref != 'refs/heads/master' &&
      github.ref != 'refs/heads/development' &&
      github.event_name == 'push' &&
      contains(github.event.head_commit.message, 'Folder2'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: Folder2
      - name: Run Folder2 specific job
        run: echo "Running Folder2 job"

  job3:
    name: Folder3 Job
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/development' ||
      (github.ref != 'refs/heads/master' &&
      github.ref != 'refs/heads/development' &&
      github.event_name == 'push' &&
      contains(github.event.head_commit.message, 'Folder3'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: Folder3
      - name: Run Folder3 specific job
        run: echo "Running Folder3 job"

  job4:
    name: Folder4 Job
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/development' ||
      (github.ref != 'refs/heads/master' &&
      github.ref != 'refs/heads/development' &&
      github.event_name == 'push' &&
      contains(github.event.head_commit.message, 'Folder4'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: Folder4
      - name: Run Folder4 specific job
        run: echo "Running Folder4 job"
